config/routes.rb
Rails.application.routes.draw do
  resources :places
  resources :trips
  root "trips#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :trip
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	has_many :destinations
	has_many :trips, through: :destinations
	has_one_attached :image

	after_create_commit { broadcast_append_to(:places) }
	after_update_commit { broadcast_replace_to(:places) }
end

app/models/trip.rb
class Trip < ApplicationRecord
	has_rich_text :purpose
	
	has_many :destinations
	has_many :places, through: :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    @places = Place.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
    
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
        format.turbo_stream {}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :zip, :image)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]

  # GET /trips or /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1 or /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    @places = Place.all.collect { |p| [p.name, p.id]}
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit([:purpose])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trippin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-800" data-controller="modal">
    <main class="max-w-7xl w-full mx-auto">
      <%= yield %>
    </main>
    <%= turbo_frame_tag :modal, data: { modal_target: "frame" } %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with model: place, html: { class: "flex flex-col", data: { action: "submit->modal#close" } } do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="flex flex-col">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="flex flex-col mt-4">
    <%= form.label :zip %>
    <%= form.number_field :zip %>
  </div>

  <div class="flex flex-col mt-4">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="flex mt-4">
    <%= form.submit class: "px-2 py-1 bg-green-500 bg-opacity-75 rounded cursor-pointer" %>
  </div>
<% end %>

app/views/places/_place.html.erb
<a href="<%= edit_place_path(place) %>" 
	class="h-96 w-full flex flex-col bg-gray-200 items-center justify-center group relative" 
	data-turbo-frame="modal" id="<%= dom_id(place) %>"
>
	<%= image_tag url_for(place.image), class: "h-96 w-full object-cover" if  place.image.attached? %>
	<div class="w-3/4 mx-auto py-2 group-hover:bg-gray-800 flex justify-center transition duration-300 absolute">
		<h3 class="text-gray-800 group-hover:text-gray-50 transition duration-300"><%= place.name %></h3>
	</div>
</a>

app/views/places/edit.html.erb
<div class="h-screen w-full flex flex-col">
	<%= turbo_frame_tag :modal do %>
		<div class="w-full fixed h-screen top-0 flex justify-center pt-40" data-modal-target="container">

			<div class="w-full h-screen bg-gray-800 bg-opacity-50 fixed top-0" data-action="click->modal#close"></div>					
			<div class="mx-auto w-3/4 lg:w-1/2 bg-gray-50 rounded-lg self-start p-4 fixed">	
				<div class="flex justify-between">
					<h1 class="text-4xl my-4 text-gray-800">Edit Place</h1>
					<a href="#" class="text-gray-800 font-semibold" data-action="modal#close">X</a>
				</div>
				<div class="w-full">
					<%= render 'form', place: @place %>
				</div>
			</div>
		</div>
	<% end %>
</div>
	

app/views/places/index.html.erb
<div class="h-screen w-full flex flex-col tw-gray-100">
  <p id="notice"><%= notice %></p>

  <h1 class="text-4xl text-gray-50 font-semibold my-4">All Places</h1>
    <%= turbo_stream_from :places %>
    <turbo-frame id="places" class="grid grid-cols-2 gap-8">
      <% @places.each do |place| %>
        <%= render "place", place: place %>
      <% end %>
    </turbo-frame>
    <%= link_to 'Add a new place', new_place_path, 
      class: "px-2 py-1 mt-4 bg-pink-400 bg-opacity-75 rounded-full text-gray-50 mr-auto",
      data: { turbo_frame: "modal" }
    %>
  </div>

app/views/places/new.html.erb
<div class="h-screen w-full flex flex-col">
	<%= turbo_frame_tag :modal do %>
		<div class="w-full fixed h-screen top-0 flex justify-center pt-40" data-modal-target="container">

			<div class="w-full h-screen bg-gray-800 bg-opacity-50 fixed top-0" data-action="click->modal#close"></div>					
			<div class="mx-auto w-3/4 lg:w-1/2 bg-gray-50 rounded-lg self-start p-4 fixed">	
				<div class="w-full flex justify-between">
					<h1 class="text-4xl my-4 text-gray-800">Create a new place</h1>
					<a href="#" class="text-gray-800 font-semibold" data-action="modal#close">X</a>
				</div>
				<div class="w-full rounded-lg p-4 bg-gray-50">
					<%= render 'form', place: @place %>
				</div>
			</div>
		</div>
	<% end %>
</div>
	

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @place.zip %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col">
    <%= form.label :purpose %>
    <%= form.rich_text_area :purpose %>
  </div>

  <div class="flex flex-col">
    <%= form.label :places %>
    <%= form.select :places, @places, {}, { multiple: false} %>
  </div>


  <div class="actions mt-4">
    <%= form.submit class: "px-2 py-1 bg-indigo-500 bg-opacity-75 text-indigo-50 rounded cursor-pointer" %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<div class="h-screen w-full flex flex-col bg-gray-50 p-4">
  <p id="notice"><%= notice %></p>

  <h1 class="text-4xl text-gray-800 font-semibold">Trips</h1>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @trips.each do |trip| %>
        <tr>
          <td><%= link_to 'Show', trip %></td>
          <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
          <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Trip', new_trip_path %>
</div>

app/views/trips/new.html.erb
<div class="h-screen w-full bg-gray-50">
	<h1 class="text-4xl my-4">New Trip</h1>

	<div class="flex flex-col mt-6 px-4">
		<%= render 'form', trip: @trip %>
		<br/>
		<%= link_to 'Cancel', trips_path %>
	</div>


</div>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-gray-50">
	<%= @trip.purpose %>
</div>
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>